apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-ef-veiviser
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  port: 8080
  ingresses:
    - https://www-q0.nav.no/familie/alene-med-barn/veiviser
  liveness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  webproxy: true
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no
    - name: LOGINSERVICE_URL
      value: https://loginservice-q.nav.no/login
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi