apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-veiviser
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    snorlax.nais.io/enabled: "true"
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: false
  ingresses:
    - https://familie.dev.nav.no/familie/alene-med-barn/veiviser
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      memory: 256Mi
  accessPolicy:
    outbound:
      external:
        - host: nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'