apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-ef-veiviser
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  port: 8080
  ingresses:
    - https://familie.dev.nav.no/familie/alene-med-barn/veiviser
  liveness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  accessPolicy:
    outbound:
      external:
        - host: nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      memory: 256Mi