name: Build app

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Bygg app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm
          registry-url: "https://npm.pkg.github.com"
        if: github.actor != 'dependabot[bot]'
      - name: Npm install build
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Npm build
        run: npm run build
